---
- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vars/java-versions.yml

  tasks:
    - include: tasks/install-java.yml
      vars:
        java_url: "{{ java_vers.server_jre_7u75.url }}"
        java_archive: "{{ java_vers.server_jre_7u75.url|basename }}"
        java_path: /tmp
